-- AlterTable
ALTER TABLE `forum` ADD COLUMN `category` ENUM('REGULAR', 'CULTURE', 'SCIENCE', 'KNOWLEDGE') NOT NULL DEFAULT 'REGULAR',
    ADD COLUMN `type` ENUM('PUBLIC', 'PENDING', 'RESTRICTED') NOT NULL DEFAULT 'PUBLIC';
